/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Models;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class BannerModel
	{
		public string Message { get; set; }
		public string ImageDesktopUrl { get; set; }
		public string ImageMobileUrl { get; set; }
		public LinkModel Link { get; set; }
		public string CssClasses { get; set; }
		public string CssClassText { get; set; }
	}
}