/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using Progress.Sitefinity.Renderer.Entities.Content;
using System;
using System.Collections.Generic;

namespace SitefinityWebApp.Mvc.Models
{
    public class CarouselModel
	{
		public string Title { get; set; }
		public List<string> ImagesDesktop { get; set; }
		public List<string> ImagesMobile { get; set; }
	}
}