/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using SitefinityWebApp.Mvc.Models.Utils;
using System.Collections.Generic;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;

namespace SitefinityWebApp.Mvc.Models
{
	public class CotizadorModel
	{
		public List<AutoData> autos { get; set; }
		public string MontoEnganche { get; set; }
	}
}