/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using System.ComponentModel;
using Progress.Sitefinity.Renderer.Entities.Content;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using SitefinityWebApp.Mvc.Models;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Modules.Libraries;
using System.Linq;
using System.Collections.Generic;
using Telerik.Sitefinity.Libraries.Model;
using System.Web.Script.Serialization;

namespace SitefinityWebApp.Mvc.Controllers
{
    [ControllerToolboxItem(Name = "Carousel_MVC", Title = "Carousel", SectionName = "CustomWidgets")]
    public class CarouselController : Controller, IPersonalizable
    {
        // GET: TestWidget
        public ActionResult Index()
        {
            var model = new CarouselModel();
            try
            {
                model.Title = this.Title;
                model.ImagesDesktop = new List<string>();
                model.ImagesMobile = new List<string>();
                if (this.ImagesMobile != null)
                    foreach (string x in this.ImagesMobile.ItemIdsOrdered)
                    {
                        model.ImagesMobile.Add(GetMediaUrlByImageId(new Guid(x), false));
                    }

                if (!string.IsNullOrEmpty(this.Images) && !string.IsNullOrEmpty(this.ImagesPath))
                {
                    var images = Newtonsoft.Json.JsonConvert.DeserializeObject<List<string>>(this.ImagesPath);
                    model.ImagesDesktop = images;
                }
                if (!string.IsNullOrEmpty(this.DesktopTexts))
                {
                    var texts = Newtonsoft.Json.JsonConvert.DeserializeObject<List<string>>(this.DesktopTexts);
                    model.DesktopTexts = texts;
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("\n\n------------------------------------\n\n" + e.Message + "\n\n------------------------------------\n\n\n");
                model.ImagesDesktop = new List<string>();
                model.ImagesMobile = new List<string>();
            }
            return View(model);
        }

        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

        public string Title { get; set; }

        [Content(Type = KnownContentTypes.Images)]
        public MixedContentContext ImagesDesktop { get; set; }

        [Content(Type = KnownContentTypes.Images)]
        public MixedContentContext ImagesMobile { get; set; }

        public string ImagesPath { get; set; }
        public string Images { get; set; }
        public string DesktopTexts { get; set; }
        //public string DesktopLinks { get; set; }

        public static string GetMediaUrlByImageId(Guid masterImageId, bool resolveAsAbsolutUrl)
        {
            var manager = LibrariesManager.GetManager();

            // Get the master version of the image
            var image = manager.GetImages().FirstOrDefault(i => i.Id == masterImageId);

            var mediaUlr = String.Empty;

            if (image != null)
            {
                // Resolve the media URL
                mediaUlr = image.ResolveMediaUrl(resolveAsAbsolutUrl);
            }

            return mediaUlr;
        }
    }
}