/* ------------------------------------------------------------------------------
<auto-generated>
    This file was generated by Sitefinity CLI v1.1.0.21
</auto-generated>
------------------------------------------------------------------------------ */

using System.ComponentModel;
using Progress.Sitefinity.Renderer.Entities.Content;
using Progress.Sitefinity.Renderer.Designers.Attributes;
using SitefinityWebApp.Mvc.Models;
using System;
using System.Web.Mvc;
using Telerik.Sitefinity.Mvc;
using Telerik.Sitefinity.Personalization;
using Telerik.Sitefinity.Modules.Libraries;
using System.Linq;
using System.Collections.Generic;

namespace SitefinityWebApp.Mvc.Controllers
{
    [ControllerToolboxItem(Name = "Carousel_MVC", Title = "Carousel", SectionName = "CustomWidgets")]
    public class CarouselController : Controller, IPersonalizable
    {
        // GET: TestWidget
        public ActionResult Index()
        {
            var model = new CarouselModel();
            try
            {
                model.Title = this.Title;
                model.ImagesDesktop = new List<string>();
                model.ImagesMobile = new List<string>();
                if (this.ImagesDesktop != null)
                    foreach (string x in this.ImagesDesktop.ItemIdsOrdered)
                    {
                        model.ImagesDesktop.Add(GetMediaUrlByImageId(new Guid(x), false));
                    }
                if (this.ImagesMobile != null)
                    foreach (string x in this.ImagesMobile.ItemIdsOrdered)
                    {
                        model.ImagesMobile.Add(GetMediaUrlByImageId(new Guid(x), false));
                    }
            }
            catch (Exception e)
            {
                Console.WriteLine("\n\n------------------------------------\n\n" + e.Message + "\n\n------------------------------------\n\n\n");
                model.ImagesDesktop = new List<string>();
                model.ImagesMobile = new List<string>();
            }
            return View(model);
        }

        protected override void HandleUnknownAction(string actionName)
        {
            this.ActionInvoker.InvokeAction(this.ControllerContext, "Index");
        }

        public string Title { get; set; }

        [Content(Type = KnownContentTypes.Images)]
        public MixedContentContext ImagesDesktop { get; set; }

        [Content(Type = KnownContentTypes.Images)]
        public MixedContentContext ImagesMobile { get; set; }

        public static string GetMediaUrlByImageId(Guid masterImageId, bool resolveAsAbsolutUrl)
        {
            var manager = LibrariesManager.GetManager();

            // Get the master version of the image
            var image = manager.GetImages().FirstOrDefault(i => i.Id == masterImageId);

            var mediaUlr = String.Empty;

            if (image != null)
            {
                // Resolve the media URL
                mediaUlr = image.ResolveMediaUrl(resolveAsAbsolutUrl);
            }

            return mediaUlr;
        }
    }
}