window.config = {
    origin: 'https://tfsmpct.com.mx/PortalTFSM/',
    //urlbase: 'https://tfsmpct.com.mx/ServicioTFSM/api/tfsm',
    //urlbase: 'https://tfs-sitefinity.virtualdreams.io:444/api/tfsm',
    urlbase: 'https://localhost:44386/api/tfsm',
    urlToyotaFinancial: 'https://toyotafinancial--salt001.lightning.force.com',
    urlToyotaCotizaciones: 'https://toyotafinancial--salt001.sandbox.my.salesforce.com',
    urlToyotaClientes: 'https://salt001-toyotaclientes.cs43.force.com',
    UrlMySalesforce: 'https://toyotafinancial--salt001.sandbox.my.salesforce.com',
    urlMyTfsm: 'https://mytfs.toyotacredito.com.mx/s/login/',
    //reCaptchaSiteKey: '6LfRuGgbAAAAAI4U4gaTCaYzgMdPZBXrav7P9UX9',
    //reCaptchaSecretKey: '6LcjOG8bAAAAAOZvGzH7X_QtizU9Kzl5Iot79WYT',
    //urlToyotaFinancial: 'https://toyotafinancial--qatfs.lightning.force.com',
    //urlToyotaCotizaciones: 'https://toyotafinancial--qatfs.my.salesforce.com',
}